# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac8081e899fffa1aca4b36dbaa08fa05fbe89c456b2b25510fc5d53d72027d713bf196a8f3f15d6506b7fa6023f80a06fc5d67b09af5d207f7f3c1a423801ced

test:
  secret_key_base: 14a69135c46731a964d7dd928a2150d4fba5855f15823912fb43f3d4634c1e7a424b38d520252c14f0418fcf230ded3e59b9252e9f1d3074b33631edfec62f85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
